DROP TABLE IF EXISTS USER_INFORMATION;
DROP TABLE IF EXISTS PRODUCT_INFORMATION;
DROP TABLE IF EXISTS USER_CART;
DROP TABLE IF EXISTS CART_ITEMS;

CREATE TABLE USER_INFORMATION (
    USER_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    username       TEXT    NOT NULL,
    password       TEXT    NOT NULL,
    email          TEXT
);

CREATE TABLE PRODUCT_INFORMATION (
    PRODUCT_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name   TEXT    NOT NULL,
    price          REAL    NOT NULL,
    stock_quantity INT     NOT NULL
);

CREATE TABLE USER_CART (
    CART_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    fk_user_id     INT     NOT NULL UNIQUE,
    FOREIGN KEY (fk_user_id) REFERENCES USER_INFORMATION(USER_ID)
);

CREATE TABLE CART_ITEMS (
    ITEM_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    fk_cart_id     INT     NOT NULL,
    fk_product_id  INT     NOT NULL,
    quantity       INT     NOT NULL,
    FOREIGN KEY (fk_cart_id) REFERENCES USER_CART(CART_ID),
    FOREIGN KEY (fk_product_id) REFERENCES PRODUCT_INFORMATION(PRODUCT_ID)
);
